### ISSUE TITLE
Headers for building

### ISSUE THREAD

**Issue by ragingonyx** [klintan/ros2_pcl_object_detection#1]
Seems like there are missing headers here, are there a set of headers that we should be using?

**Comment by luominjie19981026** [comment]
I also noticed that the pcl_object_detection.hpp is missing, would you please tell us how to get it?

**Comment by Genjutsu** [comment]
any update about the missing file ?

**Comment by klintan** [comment]
Hey,
sorry this is an old incomplete project, so the header file is unfortunately lost. Def would appreciate if someone ends up completing it if they could add a PR for it.

**Comment by aldras** [comment]
I have ported the project that this was based on to ROS2.
It might be helpful in restoring some of the header files.
At the least you can use the work I have done as a base and copy/paste the additions here back into the package.
https://github.com/aldras/multiple_object_tracking_lidar_ros2.git

You are free to copy/use any of the work I have done.

The original project that I ported is here.  The port is based on commit 27db548 on Aug 30, 2021.
https://github.com/praveen-palanisamy/multiple-object-tracking-lidar.git

**Comment by aldras** [comment]
My work to restore the original header files can be found here.
https://github.com/klintan/ros2_pcl_object_detection/pull/4
It may not have 100% functionality but it compiles and outputs data.

**Comment by klintan** [comment]
Awesome thanks! I merged that PR, so a great step in the right direction.
